apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jrsr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jrsr
    app.kubernetes.io/part-of: byoc-app-ankd
  name: jrsr
spec:
  rules:
  - host: jrsr-byoc-fcrg-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-2wz4h.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: jrsr
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
